name: Update stories
on:
  issues:
    types: [opened, closed, reopened]
jobs:
  features:
    runs-on: ubuntu-latest
    name: Update story issues
    steps:
      - name: Run epics-action
        uses: cloudaper/epics-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          epic-label-name: story
          auto-close-epic: true
